"use client";
import Link from "next/link";import {type CSSProperties,useEffect,useMemo,useRef,useState} from "react";import "./mv-studio.css";
type Mode="music"|"karaoke";type Row={time:number;original:string;literal:string;vietnamese:string};type Motion="cinematic"|"pan"|"parallax"|"still";type Atmosphere="auto"|"rain"|"fog"|"petals"|"none";type LineKey="original"|"literal"|"vietnamese";type PresetKey="period"|"modern"|"minimal"|"romantic";type TextStyle={fontFamily:string;fontSize:number;color:string;fontWeight?:number;fontStyle?:"normal"|"italic";letterSpacing?:string};
type CoverFileHandle={kind:"file";name:string;getFile:()=>Promise<File>};type CoverDirectoryHandle={kind:"directory";name:string;values:()=>AsyncIterableIterator<CoverFileHandle|{kind:"directory";name:string}>;queryPermission:(options:{mode:"read"})=>Promise<PermissionState>;requestPermission:(options:{mode:"read"})=>Promise<PermissionState>};
type WhisperChunk={text:string;timestamp?:[number|null,number|null]};type WhisperOutput={text:string;chunks?:WhisperChunk[]};type WhisperTranscriber=(audio:Float32Array,options:Record<string,unknown>)=>Promise<WhisperOutput>;type TransformersModule={pipeline:(task:string,model:string,options:Record<string,unknown>)=>Promise<WhisperTranscriber>};
const split=(v:string)=>v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const stamp=(value:number)=>`${String(Math.floor(value/60)).padStart(2,"0")}:${String(Math.floor(value%60)).padStart(2,"0")}`;
const artStyles=["Anime điện ảnh","Cổ phong Á Đông","Truyện tranh vẽ tay","Màu nước","Minh họa điện ảnh"];
const fontOptions=["Arial","Tahoma","Georgia","Times New Roman","Trebuchet MS","Verdana","Courier New"];
const lineLabels:Record<LineKey,string>={original:"LYRIC GỐC",literal:"DỊCH NGHĨA",vietnamese:"LYRIC TIẾNG VIỆT"};
const lyricPresets:Record<PresetKey,{label:string;description:string;shadow:string;styles:Record<LineKey,TextStyle>}>= {
 period:{label:"CỔ TRANG",description:"Trang nhã · ánh vàng · chất điện ảnh",shadow:"0 2px 8px #000, 0 0 18px #6d3100",styles:{original:{fontFamily:"Times New Roman",fontSize:27,color:"#f8e8c7",fontWeight:700,letterSpacing:".04em"},literal:{fontFamily:"Georgia",fontSize:19,color:"#dbc49a",fontStyle:"italic"},vietnamese:{fontFamily:"Times New Roman",fontSize:38,color:"#ffd36a",fontWeight:700,letterSpacing:".025em"}}},
 modern:{label:"HIỆN ĐẠI",description:"Sắc nét · nổi bật · dễ đọc",shadow:"0 2px 10px #000, 0 0 20px #000b",styles:{original:{fontFamily:"Trebuchet MS",fontSize:25,color:"#ffffff",fontWeight:700},literal:{fontFamily:"Arial",fontSize:19,color:"#bfe7ff",fontWeight:400},vietnamese:{fontFamily:"Arial",fontSize:36,color:"#d6ff4b",fontWeight:700,letterSpacing:".01em"}}},
 minimal:{label:"ĐƠN GIẢN",description:"Sạch · trung tính · không phân tâm",shadow:"0 2px 7px #000, 0 0 3px #000",styles:{original:{fontFamily:"Tahoma",fontSize:23,color:"#ffffff",fontWeight:600},literal:{fontFamily:"Arial",fontSize:18,color:"#d8d8d8",fontWeight:400},vietnamese:{fontFamily:"Tahoma",fontSize:33,color:"#ffffff",fontWeight:700}}},
 romantic:{label:"TÌNH CẢM",description:"Mềm mại · ấm áp · giàu cảm xúc",shadow:"0 2px 9px #000, 0 0 20px #8b315b",styles:{original:{fontFamily:"Georgia",fontSize:26,color:"#fff1f6",fontWeight:700,fontStyle:"italic"},literal:{fontFamily:"Georgia",fontSize:20,color:"#e7cfed",fontStyle:"italic"},vietnamese:{fontFamily:"Georgia",fontSize:37,color:"#ff9fc8",fontWeight:700,fontStyle:"italic"}}}
};
const audioFilePattern=/\.(wav|mp3|m4a|aac|ogg|flac|webm)$/i;
const imageFilePattern=/\.(png|jpe?g|webp|gif|avif|bmp)$/i;
export default function MVStudio(){
 const[mode,setMode]=useState<Mode>("music"),[audioUrl,setAudioUrl]=useState(""),[audioName,setAudioName]=useState(""),[duration,setDuration]=useState(0),[time,setTime]=useState(0);
 const[thumbnailUrl,setThumbnailUrl]=useState(""),[thumbnailName,setThumbnailName]=useState(""),[introDuration,setIntroDuration]=useState(3),[introActive,setIntroActive]=useState(false);
 const[images,setImages]=useState<string[]>([]),[motionClips,setMotionClips]=useState<string[]>([]),[motionClipNames,setMotionClipNames]=useState<string[]>([]),[original,setOriginal]=useState(""),[literal,setLiteral]=useState(""),[vietnamese,setVietnamese]=useState(""),[rows,setRows]=useState<Row[]>([]);
 const[textStyles,setTextStyles]=useState<Record<LineKey,TextStyle>>(lyricPresets.modern.styles),[activePreset,setActivePreset]=useState<PresetKey|"custom">("modern"),[lyricShadow,setLyricShadow]=useState(lyricPresets.modern.shadow);
 const[motionEnabled,setMotionEnabled]=useState(false),[syncing,setSyncing]=useState(false),[syncNote,setSyncNote]=useState("Chưa phân tích giọng hát."),[selectedRow,setSelectedRow]=useState(0),[aiAligning,setAiAligning]=useState(false),[aiAlignStatus,setAiAlignStatus]=useState("Sẵn sàng tự động nhận dạng và gán toàn bộ câu."),[advancedAlignOpen,setAdvancedAlignOpen]=useState(false);
 const[style,setStyle]=useState(artStyles[0]),[story,setStory]=useState(""),[motion,setMotion]=useState<Motion>("cinematic"),[atmosphere,setAtmosphere]=useState<Atmosphere>("auto"),[draggingImage,setDraggingImage]=useState<number|null>(null),[playing,setPlaying]=useState(false),[recording,setRecording]=useState(false),[note,setNote]=useState("Xuất WebM miễn phí bằng Chrome hoặc Edge.");
 const[coverFolder,setCoverFolder]=useState<CoverDirectoryHandle|null>(null),[folderSongs,setFolderSongs]=useState<CoverFileHandle[]>([]),[folderNote,setFolderNote]=useState("Chưa kết nối thư mục Cover song.");
 const[artFolder,setArtFolder]=useState<CoverDirectoryHandle|null>(null),[folderArtwork,setFolderArtwork]=useState<CoverFileHandle[]>([]),[selectedArtwork,setSelectedArtwork]=useState<string[]>([]),[artFolderNote,setArtFolderNote]=useState("Chưa kết nối thư mục Art work MV.");
 const previewRef=useRef<HTMLDivElement|null>(null),audioRef=useRef<HTMLAudioElement|null>(null),audioFileRef=useRef<File|null>(null),whisperRef=useRef<Promise<WhisperTranscriber>|null>(null),rafRef=useRef(0),introTimerRef=useRef<number|null>(null),ownedUrls=useRef<string[]>([]);
 useEffect(()=>()=>{cancelAnimationFrame(rafRef.current);if(introTimerRef.current!==null)window.clearTimeout(introTimerRef.current);ownedUrls.current.forEach(URL.revokeObjectURL)},[]);
 useEffect(()=>{void loadFolder("cover-song-folder").then(async handle=>{if(!handle)return;setCoverFolder(handle);setFolderNote(`Đã nhớ thư mục ${handle.name}.`);if(await handle.queryPermission({mode:"read"})==="granted")await listFolderSongs(handle)}).catch(()=>undefined);void loadFolder("artwork-mv-folder").then(async handle=>{if(!handle)return;setArtFolder(handle);setArtFolderNote(`Đã nhớ thư mục ${handle.name}.`);if(await handle.queryPermission({mode:"read"})==="granted")await listFolderArtwork(handle)}).catch(()=>undefined)},[]);
 const active=useMemo(()=>{let n=-1;rows.forEach((r,i)=>{if(time>=r.time)n=i});return n},[time,rows]),row=rows[Math.max(0,active)];
 const imageSpan=images.length&&duration?duration/images.length:Math.max(duration,1),imageIndex=images.length?Math.min(images.length-1,Math.floor(time/Math.max(imageSpan,.01))):0,imageProgress=images.length?Math.max(0,Math.min(1,(time-imageIndex*imageSpan)/Math.max(imageSpan,.01))):0;
 const clipSpan=motionClips.length&&duration?duration/motionClips.length:Math.max(duration,1),clipIndex=motionClips.length?Math.min(motionClips.length-1,Math.floor(time/Math.max(clipSpan,.01))):0,activeMotionClip=motionClips[clipIndex]||"";
 const bg=images[imageIndex]||"",nextBg=images[Math.min(images.length-1,imageIndex+1)]||bg,nextOpacity=imageIndex<images.length-1?Math.max(0,(imageProgress-.84)/.16):0,eased=imageProgress*imageProgress*(3-2*imageProgress);
 const direction=[[ -3,-2,3,2],[3,-1,-3,2],[-2,3,2,-3],[2,2,-2,-2]][imageIndex%4],strength=!motionEnabled||motion==="still"?0:motion==="pan"?.7:motion==="parallax"?1.35:1;
 const x=(direction[0]+(direction[2]-direction[0])*eased)*strength,y=(direction[1]+(direction[3]-direction[1])*eased)*strength,scale=!motionEnabled||motion==="still"?1:1.07+.055*eased*strength;
 const sceneStyle={backgroundImage:bg?`url("${bg}")`:undefined,transform:`translate3d(${x}%,${y}%,0) scale(${scale})`} as CSSProperties;
 const backStyle={backgroundImage:bg?`url("${bg}")`:undefined,transform:`translate3d(${x*.35}%,${y*.35}%,0) scale(${1.18+eased*.025})`} as CSSProperties;
 const nextStyle={backgroundImage:nextBg?`url("${nextBg}")`:undefined,opacity:nextOpacity,transform:`scale(${1.1-nextOpacity*.025})`} as CSSProperties;
 const activeAtmosphere:Exclude<Atmosphere,"auto">=!motionEnabled?"none":atmosphere==="auto"?(["fog","petals","rain"] as const)[imageIndex%3]:atmosphere;
 const startSync=()=>{setPlaying(true);cancelAnimationFrame(rafRef.current);const tick=()=>{const audio=audioRef.current;if(!audio||audio.paused||audio.ended)return;setTime(audio.currentTime);rafRef.current=requestAnimationFrame(tick)};tick()};
 const stopSync=()=>{setPlaying(false);cancelAnimationFrame(rafRef.current);if(audioRef.current)setTime(audioRef.current.currentTime)};
 const chooseThumbnail=(file?:File)=>{if(!file)return;const url=URL.createObjectURL(file);ownedUrls.current.push(url);setThumbnailUrl(url);setThumbnailName(file.name);setIntroActive(true);setNote("Đã có thumbnail mở đầu. Bây giờ bạn có thể nạp nhạc.")};
 const chooseImages=(files:FileList|File[]|null)=>{if(!files)return;const urls=Array.from(files).map(file=>URL.createObjectURL(file));ownedUrls.current.push(...urls);setImages(urls);setMotionEnabled(false)};
 const chooseMotionClips=(files:FileList|File[]|null)=>{if(!files)return;const chosen=Array.from(files),urls=chosen.map(file=>URL.createObjectURL(file));ownedUrls.current.push(...urls);setMotionClips(urls);setMotionClipNames(chosen.map(file=>file.name));setMotionEnabled(true)};
 const chooseAudio=(file?:File)=>{if(!file)return;const url=URL.createObjectURL(file);ownedUrls.current.push(url);audioFileRef.current=file;setAudioUrl(url);setAudioName(file.name);setRows([]);setSyncNote("Đã nạp nhạc. Hãy bấm đồng bộ theo giọng hát tiếng Việt.")};
 const listFolderSongs=async(handle:CoverDirectoryHandle)=>{const found:CoverFileHandle[]=[];for await(const entry of handle.values())if(entry.kind==="file"&&audioFilePattern.test(entry.name))found.push(entry);found.sort((a,b)=>a.name.localeCompare(b.name,"vi"));setFolderSongs(found);setFolderNote(`${found.length} bài hát trong ${handle.name}.`)};
 const connectCoverFolder=async()=>{try{let handle=coverFolder;if(!handle){const picker=(window as Window&{showDirectoryPicker?:(options:{mode:"read"})=>Promise<CoverDirectoryHandle>}).showDirectoryPicker;if(!picker){setFolderNote("Trình duyệt chưa hỗ trợ ghi nhớ thư mục. Hãy dùng Cốc Cốc/Chrome/Edge mới.");return}handle=await picker({mode:"read"});setCoverFolder(handle);await saveFolder(handle,"cover-song-folder")}let permission=await handle.queryPermission({mode:"read"});if(permission!=="granted")permission=await handle.requestPermission({mode:"read"});if(permission!=="granted"){setFolderNote("Bạn chưa cấp quyền đọc thư mục.");return}await listFolderSongs(handle)}catch{setFolderNote("Chưa kết nối được. Hãy chọn đúng thư mục F:\\COVER DỊCH NHẠC\\Cover song.")}};
 const chooseFolderSong=async(name:string)=>{if(!thumbnailUrl){setFolderNote("Hãy tải thumbnail mở đầu trước.");return}const handle=folderSongs.find(item=>item.name===name);if(handle)chooseAudio(await handle.getFile())};
 const listFolderArtwork=async(handle:CoverDirectoryHandle)=>{const found:CoverFileHandle[]=[];for await(const entry of handle.values())if(entry.kind==="file"&&imageFilePattern.test(entry.name))found.push(entry);found.sort((a,b)=>a.name.localeCompare(b.name,"vi"));setFolderArtwork(found);setArtFolderNote(`${found.length} ảnh trong ${handle.name}.`)};
 const connectArtworkFolder=async()=>{try{let handle=artFolder;if(!handle){const picker=(window as Window&{showDirectoryPicker?:(options:{mode:"read"})=>Promise<CoverDirectoryHandle>}).showDirectoryPicker;if(!picker){setArtFolderNote("Trình duyệt chưa hỗ trợ ghi nhớ thư mục.");return}handle=await picker({mode:"read"});setArtFolder(handle);await saveFolder(handle,"artwork-mv-folder")}let permission=await handle.queryPermission({mode:"read"});if(permission!=="granted")permission=await handle.requestPermission({mode:"read"});if(permission!=="granted"){setArtFolderNote("Bạn chưa cấp quyền đọc thư mục.");return}await listFolderArtwork(handle)}catch{setArtFolderNote("Hãy chọn đúng thư mục F:\\COVER DỊCH NHẠC\\Art work MV.")}};
 const loadSelectedArtwork=async()=>{const chosen=folderArtwork.filter(item=>selectedArtwork.includes(item.name));const files=await Promise.all(chosen.map(item=>item.getFile()));chooseImages(files)};
 const seekImage=(index:number)=>{const audio=audioRef.current;if(!audio||!duration||!images.length)return;audio.currentTime=index*duration/images.length;setTime(audio.currentTime)};
 const moveImage=(from:number,to:number)=>{if(from===to||to<0||to>=images.length)return;setImages(current=>{const next=[...current],[item]=next.splice(from,1);next.splice(to,0,item);return next});setDraggingImage(null)};
 const timeline=async()=>{const a=split(original),b=split(literal),c=split(vietnamese),n=Math.max(a.length,b.length,c.length);if(!n){setSyncNote("Hãy nhập lời Việt, mỗi câu một dòng.");return}if(!audioFileRef.current){setSyncNote("Hãy chọn file nhạc trước khi đồng bộ.");return}setSyncing(true);setSyncNote("Đang nghe và tìm điểm bắt đầu của từng câu hát…");try{const AudioContextClass=window.AudioContext;const context=new AudioContextClass();const buffer=await context.decodeAudioData(await audioFileRef.current.arrayBuffer());const lines=Array.from({length:n},(_,i)=>c[i]||a[i]||"");const times=detectVocalLineTimes(buffer,lines);await context.close();setRows(Array.from({length:n},(_,i)=>({time:times[i]??0,original:a[i]||"",literal:b[i]||"",vietnamese:c[i]||""})));setSelectedRow(0);setSyncNote(`Đã tự gán toàn bộ ${n} câu theo các điểm vào giọng. Dùng thanh kiểm tra để nghe và xác nhận từng câu.`)}catch{const step=(duration||n*5)/Math.max(n,1);setRows(Array.from({length:n},(_,i)=>({time:i*step,original:a[i]||"",literal:b[i]||"",vietnamese:c[i]||""})));setSelectedRow(0);setSyncNote("Không đọc được phổ âm thanh; hệ thống đã tạo mốc tạm để bạn chỉnh.")}finally{setSyncing(false)}};
 const autoAlignWhisper=async()=>{const file=audioFileRef.current,a=split(original),b=split(literal),c=split(vietnamese),n=Math.max(a.length,b.length,c.length);if(!file){setAiAlignStatus("Hãy nạp file nhạc trước.");return}if(!n||!c.length){setAiAlignStatus("Hãy nhập lời Việt, mỗi câu một dòng trước khi chạy AI.");return}setAiAligning(true);setAdvancedAlignOpen(false);try{setAiAlignStatus("Đang chuẩn hóa âm thanh về 16 kHz…");const context=new AudioContext(),decoded=await context.decodeAudioData(await file.arrayBuffer()),offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();const rendered=await offline.startRendering(),waveform=new Float32Array(rendered.getChannelData(0));await context.close();const loadWhisper=async(device:"webgpu"|"wasm")=>{const library=await(new Function("return import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1')")() as Promise<TransformersModule>);return library.pipeline("automatic-speech-recognition","onnx-community/whisper-tiny",{device,dtype:device==="webgpu"?"fp16":"q8",progress_callback:(progress:{status?:string;progress?:number;file?:string})=>{const percent=Number.isFinite(progress.progress)?` ${Math.round(progress.progress||0)}%`:"";setAiAlignStatus(`Đang tải mô hình${percent}${progress.file?` · ${progress.file.split("/").pop()}`:""}`)}})};const useWebGpu="gpu"in navigator;if(!whisperRef.current)whisperRef.current=loadWhisper(useWebGpu?"webgpu":"wasm");let transcriber:WhisperTranscriber;try{transcriber=await whisperRef.current}catch{whisperRef.current=loadWhisper("wasm");transcriber=await whisperRef.current}setAiAlignStatus("Whisper đang nghe toàn bộ bài hát và tạo timestamp từng từ…");const options={language:"vi",task:"transcribe",return_timestamps:"word",chunk_length_s:30,stride_length_s:5};let result:WhisperOutput;try{result=await transcriber(waveform,options)}catch(error){if(!useWebGpu)throw error;setAiAlignStatus("WebGPU không tương thích, đang tự chuyển sang chế độ CPU…");whisperRef.current=loadWhisper("wasm");transcriber=await whisperRef.current;result=await transcriber(waveform,options)}const lines=Array.from({length:n},(_,i)=>c[i]||a[i]||"");const aiTimes=alignLyricsToWhisper(lines,result.chunks||[],decoded.duration);setRows(Array.from({length:n},(_,i)=>({time:aiTimes[i]??0,original:a[i]||"",literal:b[i]||"",vietnamese:c[i]||""})));setSelectedRow(0);setSyncNote(`Whisper đã tự gán ${n} câu.`);setAiAlignStatus(`Hoàn tất: đã nhận dạng giọng hát và tự gán toàn bộ ${n} câu. Bấm phát MV để kiểm tra.`)}catch(error){whisperRef.current=null;setAiAlignStatus(`Whisper chưa chạy được trên trình duyệt này: ${error instanceof Error?error.message:"lỗi không xác định"}. Bạn có thể dùng chế độ tự gán nhanh bên dưới.`)}finally{setAiAligning(false)}};
 const seekAudio=(value:number)=>{const audio=audioRef.current;if(!audio)return;const next=Math.max(0,Math.min(value,duration||audio.duration||0));audio.currentTime=next;setTime(next)};
 const toggleAudio=()=>{const audio=audioRef.current;if(!audio)return;if(audio.paused)void audio.play();else audio.pause()};
 const playAssignedLine=(index:number)=>{setSelectedRow(index);seekAudio(rows[index]?.time??0);void audioRef.current?.play()};
 const captureCurrentTime=(index:number)=>{const current=audioRef.current?.currentTime??0;setRows(items=>items.map((item,i)=>i===index?{...item,time:current}:item));setSelectedRow(Math.min(index+1,Math.max(rows.length-1,0)));setSyncNote(`Đã gán câu ${index+1} tại ${stamp(current)}. Câu tiếp theo đã được chọn.`)};
 const shiftAllRows=(amount:number)=>{setRows(items=>items.map(item=>({...item,time:Math.max(0,Math.min(duration||Number.MAX_SAFE_INTEGER,item.time+amount))})));setSyncNote(`Đã dịch toàn bộ mốc ${amount>0?"trễ":"sớm"} ${Math.abs(amount).toFixed(1)} giây.`)};
 const updateTextStyle=(key:LineKey,patch:Partial<TextStyle>)=>{setActivePreset("custom");setTextStyles(current=>({...current,[key]:{...current[key],...patch}}))};
 const applyLyricPreset=(key:PresetKey)=>{const preset=lyricPresets[key];setTextStyles({original:{...preset.styles.original},literal:{...preset.styles.literal},vietnamese:{...preset.styles.vietnamese}});setLyricShadow(preset.shadow);setActivePreset(key)};
 const playFromThumbnail=()=>{const audio=audioRef.current;if(!audio||!thumbnailUrl)return;if(introTimerRef.current!==null)window.clearTimeout(introTimerRef.current);audio.pause();audio.currentTime=0;setTime(0);setPlaying(false);setIntroActive(true);setNote(`Đang chiếu thumbnail ${introDuration.toFixed(1)} giây, sau đó nhạc tự phát.`);introTimerRef.current=window.setTimeout(()=>{setIntroActive(false);introTimerRef.current=null;void audio.play()},Math.max(.5,introDuration)*1000)};
 const handleAudioEnded=()=>{stopSync();setIntroActive(Boolean(thumbnailUrl));const recorder=(window as Window&{pulseRecorder?:MediaRecorder}).pulseRecorder;if(recorder?.state==="recording")recorder.stop()};
 const prompt="Tạo tranh minh họa MV phong cách "+style+", khung hình 16:9, không chữ, nhân vật nhất quán, giàu cảm xúc. Nội dung: "+(story||"một câu chuyện âm nhạc giàu cảm xúc")+". Tạo nhiều cảnh khác nhau nhưng cùng nhân vật và bảng màu.";
 const motionPrompt=`Animate this still image into a subtle cinematic 16:9 music-video shot. Use a very slow camera push-in, gentle parallax between foreground and background, natural hair and fabric movement, soft atmospheric ${atmosphere==="rain"?"rain":atmosphere==="petals"?"falling petals":atmosphere==="fog"?"drifting mist":"particles"}. Preserve the face, hands, costume, composition and original art style. No lip sync, no sudden movement, no morphing, no text, no scene change, seamless 5-second loop.`;
 const makeArt=async()=>{await navigator.clipboard.writeText(prompt);window.open("https://chatgpt.com/","_blank","noopener,noreferrer")};
 const openMotionAI=async(url:string)=>{window.open(url,"_blank","noopener,noreferrer");try{await navigator.clipboard.writeText(motionPrompt)}catch{/* Trang AI vẫn mở nếu trình duyệt chặn clipboard. */}};
 const exportWebM=async()=>{if(!previewRef.current||!thumbnailUrl||!audioUrl||!images.length||!rows.length){setNote("Cần thumbnail, âm thanh, ảnh MV và timeline trước.");return}if(!("MediaRecorder"in window)){setNote("Trình duyệt không hỗ trợ xuất video.");return}
  setRecording(true);setNote("Đang ghi MV theo thời lượng thật…");const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});const rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm"}),chunks:Blob[]=[];
  rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const u=URL.createObjectURL(new Blob(chunks,{type:"video/webm"})),a=document.createElement("a");a.href=u;a.download=(audioName||"pulse-mv").replace(/\.[^.]+$/,"")+".webm";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);stream.getTracks().forEach(t=>t.stop());setRecording(false);setNote("Đã xuất MV WebM gồm thumbnail mở đầu.")};rec.start(1000);(window as Window&{pulseRecorder?:MediaRecorder}).pulseRecorder=rec;playFromThumbnail();setNote("Đang xuất: thumbnail chạy trước, sau đó nhạc tự phát; video tự dừng khi hết bài.");
 };
 const stop=()=>{const w=window as Window&{pulseRecorder?:MediaRecorder};if(w.pulseRecorder?.state==="recording")w.pulseRecorder.stop()};
 return <main className="mv-shell"><header><Link href="/">PULSE</Link><nav><Link href="/studio/">LYRIC STUDIO</Link><b>MV STUDIO</b></nav></header>
 <section className="mv-hero"><p>FREE MV WORKSHOP</p><h1>Biến bài hát thành<br/><em>một thế giới có hình.</em></h1><span>Xử lý trên thiết bị · không tải âm thanh riêng tư lên máy chủ.</span></section>
 <div className="mode-tabs"><button className={mode==="music"?"on":""} onClick={()=>setMode("music")}>MV CA NHẠC</button><button className={mode==="karaoke"?"on":""} onClick={()=>setMode("karaoke")}>MV KARAOKE</button></div>
 <section className="mv-grid"><div className="mv-controls">
 <article className="thumbnail-step"><h2>01 · Thumbnail mở đầu</h2><p>Ảnh này xuất hiện trước; hết thời gian đặt bên dưới thì nhạc mới bắt đầu.</p><label className="upload">TẢI ẢNH THUMBNAIL<input type="file" accept="image/*" onChange={e=>chooseThumbnail(e.target.files?.[0])}/></label>{thumbnailUrl&&<img className="thumbnail-thumb" src={thumbnailUrl} alt="Thumbnail mở đầu"/>}<p>{thumbnailName||"Chưa chọn thumbnail"}</p><label>THỜI GIAN HIỂN THỊ TRƯỚC NHẠC<div className="duration-field"><input type="range" min=".5" max="10" step=".5" value={introDuration} onChange={e=>setIntroDuration(Number(e.target.value))}/><input type="number" min=".5" max="10" step=".5" value={introDuration} onChange={e=>setIntroDuration(Math.max(.5,Number(e.target.value)||.5))}/><span>GIÂY</span></div></label></article>
 <article className={!thumbnailUrl?"step-locked":""}><h2>02 · Âm thanh</h2>{!thumbnailUrl&&<p className="locked-note">Tải thumbnail ở bước 01 để mở phần nhạc.</p>}<button className="folder-connect" disabled={!thumbnailUrl} type="button" onClick={connectCoverFolder}>📁 KẾT NỐI THƯ MỤC COVER SONG</button><p className="folder-path">F:\COVER DỊCH NHẠC\Cover song</p>{folderSongs.length>0&&<label>CHỌN BÀI TỪ THƯ MỤC<select disabled={!thumbnailUrl} defaultValue="" onChange={e=>void chooseFolderSong(e.target.value)}><option value="" disabled>Chọn bài hát…</option>{folderSongs.map(song=><option value={song.name} key={song.name}>{song.name}</option>)}</select></label>}<p>{folderNote}</p><label className={`upload ${!thumbnailUrl?"disabled":""}`}>HOẶC TẢI {mode==="music"?"BÀI HÁT ĐÃ THÂU":"NHẠC KHÔNG LỜI"}<input disabled={!thumbnailUrl} type="file" accept="audio/*" onChange={e=>chooseAudio(e.target.files?.[0])}/></label><p>{audioName||"Chưa chọn file"}</p></article>
 <article><h2>03 · Tranh minh họa</h2><select value={style} onChange={e=>setStyle(e.target.value)}>{artStyles.map(x=><option key={x}>{x}</option>)}</select><textarea value={story} onChange={e=>setStory(e.target.value)} placeholder="Câu chuyện, nhân vật, bối cảnh…"/><button onClick={makeArt}>TẠO PROMPT & MỞ CHATGPT FREE ↗</button><button className="folder-connect art-folder" type="button" onClick={connectArtworkFolder}>🖼 KẾT NỐI THƯ MỤC ART WORK MV</button><p className="folder-path">F:\COVER DỊCH NHẠC\Art work MV</p>{folderArtwork.length>0&&<><label>CHỌN NHIỀU ẢNH TỪ THƯ MỤC<select className="artwork-select" multiple size={Math.min(7,folderArtwork.length)} value={selectedArtwork} onChange={e=>setSelectedArtwork(Array.from(e.target.selectedOptions,option=>option.value))}>{folderArtwork.map(item=><option value={item.name} key={item.name}>{item.name}</option>)}</select></label><button type="button" disabled={!selectedArtwork.length} onClick={()=>void loadSelectedArtwork()}>NẠP {selectedArtwork.length||""} ẢNH ĐÃ CHỌN</button></>}<p>{artFolderNote}</p><label className="upload secondary">HOẶC TẢI TRANH TỪ MÁY<input multiple type="file" accept="image/*" onChange={e=>chooseImages(e.target.files)}/></label>{images.length>0&&<><p className="schedule-tip">KÉO THẢ HOẶC DÙNG ← → ĐỂ ĐỔI THỨ TỰ</p><div className="image-schedule">{images.map((url,index)=>{const start=duration?index*duration/images.length:0,end=duration?(index+1)*duration/images.length:0;return <div className={`image-card ${index===imageIndex?"active":""} ${draggingImage===index?"dragging":""}`} key={url} draggable onDragStart={()=>setDraggingImage(index)} onDragOver={event=>event.preventDefault()} onDrop={()=>draggingImage!==null&&moveImage(draggingImage,index)}><button type="button" className="image-main" onClick={()=>seekImage(index)}><img src={url} alt={`Ảnh ${index+1}`}/><span><b>ẢNH {String(index+1).padStart(2,"0")}</b><small>{duration?`${stamp(start)} — ${stamp(end)}`:"CHỜ THỜI LƯỢNG NHẠC"}</small></span></button><div className="image-order"><button type="button" disabled={index===0} onClick={()=>moveImage(index,index-1)} aria-label={`Đưa ảnh ${index+1} sang trái`}>←</button><button type="button" disabled={index===images.length-1} onClick={()=>moveImage(index,index+1)} aria-label={`Đưa ảnh ${index+1} sang phải`}>→</button></div></div>})}</div></>}<p>{images.length} ảnh · {images.length&&duration?`${(duration/images.length).toFixed(1)} giây/ảnh · `:""}phân bố đều toàn MV</p></article>
 <article className="animate-lab"><h2>04 · Animate Lab — Làm ảnh chuyển động</h2><p className="animate-intro">Luôn có hai phương án: chuyển động trực tiếp miễn phí trên máy, hoặc dùng AI image-to-video rồi nạp clip trở lại hệ thống.</p><section className="motion-method direct-motion"><header><i>01</i><span><b>CHUYỂN ĐỘNG TRỰC TIẾP</b><small>Không cần AI · không tốn credit</small></span></header><button type="button" className="motion-apply" disabled={!images.length} onClick={()=>setMotionEnabled(value=>!value)}>{!images.length?"HÃY NẠP ẢNH Ở BƯỚC 03":motionEnabled?"✓ ĐÃ BẬT — BẤM ĐỂ TẮT":"TẠO SLOW PAN + PARALLAX NGAY"}</button><div className="visual-motion"><label>CHUYỂN ĐỘNG<select disabled={!images.length} value={motion} onChange={e=>setMotion(e.target.value as Motion)}><option value="cinematic">Slow pan + parallax</option><option value="pan">Slow pan nhẹ</option><option value="parallax">Parallax rõ</option><option value="still">Ảnh tĩnh</option></select></label><label>KHÔNG KHÍ<select disabled={!images.length} value={atmosphere} onChange={e=>setAtmosphere(e.target.value as Atmosphere)}><option value="auto">Tự động luân phiên</option><option value="rain">Mưa nhẹ</option><option value="fog">Sương trôi</option><option value="petals">Cánh hoa</option><option value="none">Không hiệu ứng</option></select></label></div></section><section className="motion-method ai-motion"><header><i>02</i><span><b>MỞ AI TẠO ẢNH ĐỘNG</b><small>Không tạo trực tiếp được thì chuyển sang dịch vụ AI tương ứng</small></span></header><textarea readOnly value={motionPrompt} aria-label="Prompt tạo ảnh chuyển động"/><div className="ai-provider-buttons"><button type="button" onClick={()=>void openMotionAI("https://app.pixverse.ai/")}><b>MỞ PIXVERSE ↗</b><small>Tạo Image to Video</small></button><button type="button" onClick={()=>void openMotionAI("https://hailuoai.video/tools/image-to-video")}><b>MỞ HAILUO ↗</b><small>Tạo Image to Video</small></button></div>{images.length>0?<a className="motion-download" href={images[imageIndex]} download={`mv-source-${imageIndex+1}.png`}>↓ TẢI ẢNH ĐANG CHỌN ĐỂ ĐƯA VÀO AI</a>:<p className="ai-link-ready">Bạn có thể mở trang AI ngay. Sau đó tải ảnh từ máy lên dịch vụ đã chọn.</p>}<p className="ai-free-note">Nút sẽ mở thẳng công cụ AI và tự sao chép prompt chuyển động. Tạo clip khoảng 5 giây, tỉ lệ 16:9; lượt miễn phí và watermark tùy tài khoản từng dịch vụ.</p><label className="upload ai-video-upload">NẠP CÁC CLIP AI MP4/WEBM ĐÃ TẠO<input multiple type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>chooseMotionClips(e.target.files)}/></label>{motionClipNames.length>0&&<div className="clip-summary"><b>{motionClipNames.length} CLIP AI ĐANG DÙNG</b>{motionClipNames.map((name,index)=><small key={`${name}-${index}`}>{String(index+1).padStart(2,"0")} · {name}</small>)}<button type="button" onClick={()=>{setMotionClips([]);setMotionClipNames([])}}>BỎ CLIP AI · QUAY LẠI ẢNH</button></div>}</section></article>
 <article className="lyrics-editor"><h2>04 · Lyric và kiểu chữ</h2><label>LỜI GỐC<textarea value={original} onChange={e=>setOriginal(e.target.value)} placeholder="Mỗi câu một dòng"/></label>{mode==="music"&&<label>DỊCH SÁT NGHĨA<textarea value={literal} onChange={e=>setLiteral(e.target.value)} placeholder="Mỗi câu một dòng"/></label>}<label>LỜI VIỆT<textarea value={vietnamese} onChange={e=>setVietnamese(e.target.value)} placeholder="Mỗi câu một dòng; hệ thống dùng các câu này để đồng bộ với giọng hát"/></label><h3>GỢI Ý PHONG CÁCH HIỂN THỊ</h3><div className="lyric-preset-grid">{(Object.keys(lyricPresets) as PresetKey[]).map(key=>{const preset=lyricPresets[key];return <button type="button" className={`lyric-preset ${activePreset===key?"on":""}`} data-preset={key} key={key} onClick={()=>applyLyricPreset(key)}><span className="preset-sample" style={{fontFamily:preset.styles.vietnamese.fontFamily,color:preset.styles.vietnamese.color,textShadow:preset.shadow}}>Aa</span><b>{preset.label}</b><small>{preset.description}</small><i><em style={{background:preset.styles.original.color}}/><em style={{background:preset.styles.literal.color}}/><em style={{background:preset.styles.vietnamese.color}}/></i></button>})}</div>{activePreset==="custom"&&<p className="custom-style-note">ĐANG DÙNG KIỂU TÙY CHỈNH</p>}<div className="text-style-grid">{(["original","literal","vietnamese"] as LineKey[]).map(key=><section className="text-style-card" key={key}><b>{lineLabels[key]}</b><label>FONT<select value={textStyles[key].fontFamily} onChange={e=>updateTextStyle(key,{fontFamily:e.target.value})}>{fontOptions.map(font=><option key={font} value={font}>{font}</option>)}</select></label><label>CỠ CHỮ<div className="font-size-field"><input type="range" min="12" max="64" value={textStyles[key].fontSize} onChange={e=>updateTextStyle(key,{fontSize:Number(e.target.value)})}/><input type="number" min="12" max="64" value={textStyles[key].fontSize} onChange={e=>updateTextStyle(key,{fontSize:Number(e.target.value)})}/></div></label><label>MÀU CHỮ<div className="color-field"><input type="color" value={textStyles[key].color} onChange={e=>updateTextStyle(key,{color:e.target.value})}/><code>{textStyles[key].color.toUpperCase()}</code></div></label></section>)}</div><div className="whisper-auto"><header><i>AI</i><span><b>WHISPER AUTO ALIGN</b><small>Tự nghe giọng hát · tự gán toàn bộ câu</small></span></header><button type="button" disabled={aiAligning||!audioUrl||!vietnamese.trim()} onClick={()=>void autoAlignWhisper()}>{aiAligning?"AI ĐANG NGHE VÀ GÁN TOÀN BỘ…":"⚡ TỰ ĐỘNG NHẬN DẠNG + GÁN TẤT CẢ"}</button><p>{aiAlignStatus}</p><small>Lần đầu hệ thống tải mô hình nhận dạng; các lần sau trình duyệt sẽ dùng lại. File nhạc được xử lý ngay trên máy.</small></div><button className="fast-align" type="button" disabled={syncing} onClick={()=>void timeline()}>{syncing?"ĐANG PHÂN TÍCH…":"TỰ GÁN NHANH (KHÔNG AI)"}</button><p className="sync-note">{syncNote}</p></article>
 {rows.length>0&&<article className={`alignment-studio ${advancedAlignOpen?"open":""}`}><button type="button" className="advanced-toggle" onClick={()=>setAdvancedAlignOpen(open=>!open)}>{advancedAlignOpen?"ẨN TINH CHỈNH NÂNG CAO":"MỞ TINH CHỈNH NÂNG CAO (NẾU CẦN)"}</button>{advancedAlignOpen&&<><h2>05 · Tinh chỉnh câu nâng cao</h2><p>Chỉ dùng phần này nếu muốn sửa một mốc thời gian sau khi hệ thống đã tự gán.</p><div className="align-toolbar"><div className="align-head"><b>ĐANG CHECK CÂU {selectedRow+1}/{rows.length}</b><time>{stamp(time)} / {stamp(duration)}</time></div><input className="song-scrubber" aria-label="Tua bài hát" type="range" min="0" max={Math.max(duration,.1)} step=".05" value={Math.min(time,duration||0)} onChange={e=>seekAudio(Number(e.target.value))}/><div className="transport"><button type="button" onClick={()=>seekAudio(0)}>↺ ĐẦU BÀI</button><button type="button" onClick={()=>seekAudio(time-5)}>−5 GIÂY</button><button type="button" className="play-check" onClick={toggleAudio}>{playing?"❚❚ TẠM DỪNG":"▶ PHÁT"}</button><button type="button" onClick={()=>seekAudio(time+5)}>+5 GIÂY</button><button type="button" onClick={()=>playAssignedLine(selectedRow)}>NGHE CÂU ĐANG CHỌN</button></div><div className="assignment-nav"><button type="button" disabled={selectedRow===0} onClick={()=>setSelectedRow(i=>Math.max(0,i-1))}>← CÂU TRƯỚC</button><button type="button" disabled={selectedRow===rows.length-1} onClick={()=>setSelectedRow(i=>Math.min(rows.length-1,i+1))}>CÂU SAU →</button></div><div className="current-assignment"><small>CÂU SẼ ĐƯỢC GÁN TẠI {stamp(time)}</small><b>{rows[selectedRow]?.vietnamese||rows[selectedRow]?.original}</b><button type="button" onClick={()=>captureCurrentTime(selectedRow)}>✓ GÁN CÂU NÀY TẠI VỊ TRÍ ĐANG PHÁT</button></div><div className="bulk-assign"><button type="button" disabled={syncing} onClick={()=>void timeline()}>{syncing?"ĐANG PHÂN TÍCH…":"⚡ TỰ GÁN LẠI TẤT CẢ"}</button><button type="button" onClick={()=>shiftAllRows(-.3)}>TOÀN BỘ SỚM 0.3S</button><button type="button" onClick={()=>shiftAllRows(.3)}>TOÀN BỘ TRỄ 0.3S</button></div></div><div className="time-list">{rows.map((r,i)=><div className={`time-row ${i===active?"active":""} ${i===selectedRow?"selected":""}`} key={i}><button type="button" className="line-preview" onClick={()=>playAssignedLine(i)}><i>{String(i+1).padStart(2,"0")}</i><span>{stamp(r.time)}</span></button><input aria-label={`Mốc câu ${i+1}`} type="number" step=".1" value={r.time.toFixed(1)} onFocus={()=>setSelectedRow(i)} onChange={e=>setRows(x=>x.map((q,j)=>j===i?{...q,time:Number(e.target.value)}:q))}/><textarea aria-label={`Lời Việt câu ${i+1}`} value={r.vietnamese} onFocus={()=>setSelectedRow(i)} onChange={e=>setRows(x=>x.map((q,j)=>j===i?{...q,vietnamese:e.target.value}:q))}/><button type="button" onClick={()=>captureCurrentTime(i)}>GÁN TẠI ĐÂY</button></div>)}</div></>}</article>}
 </div><div className="mv-preview-wrap"><div ref={previewRef} className={`mv-preview mv-scene ${playing?"playing":"paused"} ${activeMotionClip?"has-motion-clip":""}`}><div className="scene-back" style={backStyle}/><div className="scene-image" style={sceneStyle}/><div className="scene-image scene-next" style={nextStyle}/>{activeMotionClip&&<video className="scene-video" key={activeMotionClip} src={activeMotionClip} autoPlay muted loop playsInline/>}<div className="scene-shade"/>{activeAtmosphere==="rain"&&<div className="weather rain"/>}{activeAtmosphere==="fog"&&<div className="weather fog"><i/><i/></div>}{activeAtmosphere==="petals"&&<div className="weather petals">{Array.from({length:14},(_,i)=><i key={i} style={{"--i":i,left:`${(i*7.3)%100}%`,animationDelay:`-${(i*.73)%6}s`,animationDuration:`${5+(i%5)*.7}s`} as CSSProperties}/>)}</div>}{row&&<>{mode==="music"&&<div className="top-lyrics"><b style={{...textStyles.original,textShadow:lyricShadow}}>{row.original}</b><span style={{...textStyles.literal,textShadow:lyricShadow}}>{row.literal}</span></div>}<div className="bottom-lyrics">{mode==="karaoke"&&<span style={{...textStyles.original,textShadow:lyricShadow}}>{row.original}</span>}<b style={{...textStyles.vietnamese,textShadow:lyricShadow}}>{row.vietnamese}</b></div></>}{thumbnailUrl&&introActive&&<div className="mv-intro" style={{backgroundImage:`url("${thumbnailUrl}")`}}><span>THUMBNAIL · {introDuration.toFixed(1)} GIÂY</span></div>}</div>
 {audioUrl?<><button type="button" className="play-intro" disabled={!thumbnailUrl} onClick={playFromThumbnail}>▶ PHÁT MV TỪ THUMBNAIL RỒI VÀO NHẠC</button><audio ref={audioRef} src={audioUrl} controls onLoadedMetadata={e=>setDuration(e.currentTarget.duration)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={()=>{setIntroActive(false);startSync()}} onPause={stopSync} onEnded={handleAudioEnded}/></>:<div className="audio-empty">Chưa có âm thanh</div>}
 <div className="render-card"><button onClick={recording?stop:exportWebM} disabled={!thumbnailUrl||!audioUrl||!images.length||!rows.length}>{recording?"DỪNG & TẢI VIDEO":"XUẤT MV .WEBM"}</button><p>{note}</p><small>Video xuất ra sẽ có thumbnail mở đầu, sau đó mới phát nhạc; font, cỡ và màu của cả ba dòng được giữ nguyên.</small></div></div></section></main>
}

function folderDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open("pulse-mv-folders",1);request.onupgradeneeded=()=>request.result.createObjectStore("handles");request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveFolder(handle:CoverDirectoryHandle,key:string){const db=await folderDb();await new Promise<void>((resolve,reject)=>{const transaction=db.transaction("handles","readwrite");transaction.objectStore("handles").put(handle,key);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)});db.close()}
async function loadFolder(key:string){const db=await folderDb();const handle=await new Promise<CoverDirectoryHandle|null>((resolve,reject)=>{const request=db.transaction("handles").objectStore("handles").get(key);request.onsuccess=()=>resolve((request.result as CoverDirectoryHandle|undefined)??null);request.onerror=()=>reject(request.error)});db.close();return handle}

function detectVocalLineTimes(buffer:AudioBuffer,lines:string[]){
 const frameSeconds=.04,frameSize=Math.max(1,Math.floor(buffer.sampleRate*frameSeconds)),frameCount=Math.max(1,Math.ceil(buffer.length/frameSize)),sampleStride=Math.max(1,Math.floor(buffer.sampleRate/8000));
 const channels=Array.from({length:buffer.numberOfChannels},(_,index)=>buffer.getChannelData(index)),energy=new Array<number>(frameCount).fill(0);
 for(let frame=0;frame<frameCount;frame++){const start=frame*frameSize,end=Math.min(buffer.length,start+frameSize);let sum=0,samples=0;for(let position=start;position<end;position+=sampleStride){let mono=0;for(const channel of channels)mono+=channel[position]||0;mono/=channels.length;sum+=mono*mono;samples++}energy[frame]=Math.sqrt(sum/Math.max(samples,1))}
 const smooth=energy.map((_,index)=>{let sum=0,count=0;for(let offset=-2;offset<=2;offset++){const value=energy[index+offset];if(value!==undefined){sum+=value;count++}}return sum/Math.max(count,1)}),sorted=[...smooth].sort((a,b)=>a-b);
 const quantile=(ratio:number)=>sorted[Math.min(sorted.length-1,Math.max(0,Math.floor((sorted.length-1)*ratio)))]||0,floor=quantile(.18),peak=quantile(.92),range=Math.max(peak-floor,1e-6),threshold=floor+range*.2,lookBack=Math.max(2,Math.round(.4/frameSeconds));
 const candidates:Array<{time:number;score:number}>=[];
 for(let index=lookBack;index<smooth.length-2;index++){let before=0;for(let offset=1;offset<=lookBack;offset++)before+=smooth[index-offset];before/=lookBack;const rise=smooth[index]-before,localPeak=smooth[index]>=smooth[index-1]&&smooth[index]>=smooth[index+1];if(smooth[index]>threshold&&rise>range*.025&&localPeak)candidates.push({time:index*frameSeconds,score:rise/range+(smooth[index]-threshold)/range*.35})}
 const duration=buffer.duration,count=lines.length;if(!count)return[];
 const introWindow=Math.min(duration*.28,Math.max(14,duration/Math.max(count,1)*3)),early=candidates.filter(item=>item.time>=.25&&item.time<=introWindow),first=(early.sort((a,b)=>(b.score-b.time/duration*.22)-(a.score-a.time/duration*.22))[0]?.time)??Math.min(2,duration*.04);
 const weights=lines.map(line=>Math.max(1,Math.pow(line.trim().split(/\s+/).filter(Boolean).length,.72))),weightTotal=weights.reduce((sum,value)=>sum+value,0),usableEnd=Math.max(first,duration*.965),times:number[]=[];let usedWeight=0,previous=Math.max(0,first-.3);
 for(let index=0;index<count;index++){const target=first+(usableEnd-first)*(usedWeight/Math.max(weightTotal,1)),averageSpan=(usableEnd-first)/Math.max(count,1),window=Math.max(1.4,averageSpan*.72),available=candidates.filter(item=>item.time>previous+.22&&Math.abs(item.time-target)<=window);let selected=target;if(available.length)selected=available.reduce((best,item)=>item.score-Math.abs(item.time-target)/window*.75>best.score-Math.abs(best.time-target)/window*.75?item:best).time;selected=Math.max(previous+.22,Math.min(selected,duration-.05));times.push(selected);previous=selected;usedWeight+=weights[index]}
 return times;
}

function normalizeWords(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/đ/g,"d").replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(Boolean)}
function tokenScore(a:string,b:string){if(a===b)return 1;if(a.length>3&&b.length>3&&(a.startsWith(b)||b.startsWith(a)))return .75;if(Math.abs(a.length-b.length)>1)return 0;let differences=0,left=0,right=0;while(left<a.length&&right<b.length){if(a[left]===b[right]){left++;right++;continue}differences++;if(differences>1)return 0;if(a.length>b.length)left++;else if(b.length>a.length)right++;else{left++;right++}}return .55}
function alignLyricsToWhisper(lines:string[],chunks:WhisperChunk[],duration:number){
 const spoken:Array<{word:string;time:number}>=[];for(const chunk of chunks){const words=normalizeWords(chunk.text),start=Number(chunk.timestamp?.[0]??0),rawEnd=chunk.timestamp?.[1],end=typeof rawEnd==="number"?rawEnd:start+Math.max(.35,words.length*.38);words.forEach((word,index)=>spoken.push({word,time:start+(end-start)*index/Math.max(words.length,1)}))}
 if(!spoken.length){const step=duration/Math.max(lines.length,1);return lines.map((_,index)=>index*step)}const lyricTokens=lines.map(normalizeWords),total=lyricTokens.reduce((sum,words)=>sum+Math.max(words.length,1),0),times:number[]=[];let consumed=0,previous=-1;
 for(const words of lyricTokens){const expected=Math.round(consumed/Math.max(total,1)*(spoken.length-1)),radius=Math.max(14,Math.round(spoken.length/Math.max(lines.length,1)*2.3)),low=Math.max(previous+1,expected-radius),high=Math.min(spoken.length-1,expected+radius);let bestIndex=Math.max(low,Math.min(expected,high)),bestScore=-1;for(let candidate=low;candidate<=high;candidate++){const window=spoken.slice(candidate,Math.min(spoken.length,candidate+Math.max(words.length+3,6))).map(item=>item.word);let hits=0;for(const word of words){let match=0;for(const heard of window)match=Math.max(match,tokenScore(word,heard));hits+=match}const textScore=hits/Math.max(words.length,1),distancePenalty=Math.abs(candidate-expected)/Math.max(radius,1)*.22,score=textScore-distancePenalty;if(score>bestScore){bestScore=score;bestIndex=candidate}}if(bestScore<.14)bestIndex=Math.max(previous+1,Math.min(expected,spoken.length-1));times.push(Math.max(0,spoken[bestIndex]?.time??0));previous=bestIndex;consumed+=Math.max(words.length,1)}
 return times;
}
